#####  Basic Operations on Images



In [28]:
import cv2
import numpy as np
img = cv2.imread('mountain.jpg')


In [ ]:
cv2.namedWindow('mountain', cv2.WINDOW_NORMAL)
cv2.imshow('mountain',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [15]:
px = img[100,100]
print (px)


[205 141  77]


In [18]:
# accessing only blue pixel
blue = img[100,100,0]
print (blue)

205


In [48]:
img[100,100] = [255,255,255]
print (img[100,100])

[255 255 255]


In [51]:
img[100:200,100:200] = [0,255,0]
print (img[100,100])

[  0 255   0]


In [52]:
cv2.namedWindow('mountain', cv2.WINDOW_NORMAL)
cv2.imshow('mountain',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
img[500:700,200:400,2] = 255


In [59]:
cv2.namedWindow('mountain', cv2.WINDOW_NORMAL)
cv2.imshow('mountain',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [46]:
# accessing RED value
img.item(10,10,2)

100

In [32]:
# modifying RED value
img.itemset((10,10,2),100)
img.item(10,10,2)

100

In [34]:
 print (img.shape)

(183, 275, 3)


In [36]:
print (img.size)


150975


In [38]:
print (img.dtype)


uint8
